import { useState } from "react";

import {

    useLocation,
    useNavigate

} from "react-router-dom";


import {

    Code2,
    Play

} from "lucide-react";






function CodeGeneration(){


const location = useLocation();

const navigate = useNavigate();



const {

    test_cases,

    user_story,

    repository

} = location.state || {};




const [code,setCode] =
useState("");



const [loading,setLoading] =
useState(false);






function generateCode(){



setLoading(true);



setTimeout(()=>{


const generated = `

# Generated by TestForge AI
# Framework : PyTest + Selenium


import pytest

from selenium import webdriver



class TestGeneratedFlow:



    def setup_method(self):

        self.driver = webdriver.Chrome()



    def teardown_method(self):

        self.driver.quit()






    def test_user_requirement(self):

        """

        User Story:

        ${user_story}


        Generated Test Cases:

        ${JSON.stringify(
            test_cases,
            null,
            2
        )}

        """



        driver = self.driver


        driver.get(
            "http://localhost:5173"
        )



        assert driver.title != ""




    def test_negative_validation(self):


        assert True




`;


setCode(
    generated
);


setLoading(false);


},1500);



}









return(

<div>



<h1 className="text-2xl font-bold mb-6">

Automation Code Generator

</h1>









<div
className="
bg-white
border
rounded-xl
p-6
mb-6
"
>


<h2 className="font-bold mb-3">

Input Summary

</h2>



<p>

<b>Repository :</b>{" "}

{
repository?.name
||
"Loaded Repo"
}

</p>



<p>

<b>Framework :</b>

 PyTest + Selenium

</p>




</div>











<button

onClick={generateCode}


className="
bg-blue-600
text-white
px-5
py-3
rounded-lg
flex
gap-2
"

>


<Code2/>


{

loading

?

"Generating..."

:

"Generate Automation Code"

}


</button>











{

code &&



<div
className="
mt-6
bg-gray-900
text-green-400
rounded-xl
p-5
"
>


<pre className="whitespace-pre-wrap">

{code}

</pre>







<button


onClick={()=>{


navigate(

"/execution",

{

state:{


generated_code:

code,


test_cases:


test_cases


}


}

);


}}



className="
mt-6
bg-green-600
text-white
px-5
py-3
rounded-lg
flex
gap-2
"


>



<Play/>


Execute Tests



</button>




</div>


}



</div>


);


}




export default CodeGeneration;