import {
    Download,
    FileText,
    Code2,
    Bug,
    FileArchive
} from "lucide-react";





function Export(){





function downloadFile(
    filename,
    content
){



if(!content){


alert(
"No data available to export"
);


return;


}




const blob =
new Blob(

[
content
],

{
type:"text/plain"
}

);



const url =
URL.createObjectURL(
blob
);



const link =
document.createElement(
"a"
);



link.href=url;


link.download=
filename;



link.click();



URL.revokeObjectURL(
url
);



}









const testCases =

localStorage.getItem(
"testCases"
);



const generatedCode =

localStorage.getItem(
"generatedCode"
);



const executionReport =

localStorage.getItem(
"executionReport"
);








const fullReport = `


==============================
 TESTFORGE AI QA REPORT
==============================


1. GENERATED TEST CASES
-----------------------

${testCases || "No test cases"}




2. AUTOMATION CODE
-----------------------

${generatedCode || "No code generated"}




3. EXECUTION + BUG ANALYSIS
-----------------------

${executionReport || "No execution report"}




Generated By:

TestForge AI
Agentic QA Automation Platform

`;









return(

<div>






<h1 className="
text-2xl
font-bold
mb-6
">

Export Center

</h1>





<p className="
text-gray-500
mb-8
">

Download generated QA artifacts

</p>









<div className="
grid
grid-cols-4
gap-6
">







{/* TEST CASES */}


<div className="
bg-white
border
rounded-xl
p-6
">


<FileText
size={40}
className="text-blue-600"
/>



<h2 className="
font-bold
mt-5
">

Test Cases

</h2>



<p className="
text-gray-500
my-3
">

AI generated scenarios

</p>




<button

onClick={()=>{


downloadFile(

"test_cases.json",

testCases

)


}}


className="
bg-blue-600
text-white
px-5
py-2
rounded-lg
"

>

Download

</button>




</div>










{/* CODE */}


<div className="
bg-white
border
rounded-xl
p-6
">


<Code2
size={40}
className="text-green-600"
/>



<h2 className="
font-bold
mt-5
">

Automation Code

</h2>



<p className="
text-gray-500
my-3
">

PyTest Selenium script

</p>




<button

onClick={()=>{


downloadFile(

"automation_test.py",

generatedCode

)


}}


className="
bg-green-600
text-white
px-5
py-2
rounded-lg
"

>

Download

</button>



</div>











{/* EXECUTION */}


<div className="
bg-white
border
rounded-xl
p-6
">


<Bug
size={40}
className="text-red-600"
/>



<h2 className="
font-bold
mt-5
">

Execution Report

</h2>



<p className="
text-gray-500
my-3
">

Bug analysis report

</p>




<button


onClick={()=>{


downloadFile(

"execution_report.json",

executionReport

)


}}



className="
bg-red-600
text-white
px-5
py-2
rounded-lg
"

>

Download

</button>




</div>











{/* FULL REPORT */}


<div className="
bg-white
border
rounded-xl
p-6
">


<FileArchive
size={40}
className="text-purple-600"
/>



<h2 className="
font-bold
mt-5
">

Full QA Report

</h2>




<p className="
text-gray-500
my-3
">

Complete workflow export

</p>




<button


onClick={()=>{


downloadFile(

"TestForge_AI_Report.txt",

fullReport

)


}}


className="
bg-purple-600
text-white
px-5
py-2
rounded-lg
"

>


Download


</button>




</div>








</div>




</div>


);


}



export default Export;